const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const backdrop = $('#modalBackdrop'); const checkout = $('#checkoutModal'); const success = $('#successModal');
let currentPlan = {name:'Momentum', price:799};
function openModal(el){backdrop.classList.add('open');el.classList.add('open')}
function closeModals(){backdrop.classList.remove('open');$$('.modal').forEach(x=>x.classList.remove('open'))}
function selectPlan(name, price){currentPlan={name,price};$('#selectedPlan').textContent=name;$('#selectedPrice').textContent=`₹${price}/mo`;$('#payAmount').textContent=`₹${price}`;openModal(checkout)}
$$('.choose-btn').forEach(b=>b.onclick=()=>selectPlan(b.dataset.plan,b.dataset.price));
$('#exploreBtn').onclick=()=>$('#plans').scrollIntoView();
$$('[data-close]').forEach(b=>b.onclick=closeModals);backdrop.onclick=closeModals;
$$('.method').forEach(b=>b.onclick=()=>{$$('.method').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
function showActivation(result){closeModals();$('#successModal p').textContent=result.message || `Your ${result.plan} plan is now active until ${result.renewal}. We have emailed your confirmation and notified the network team.`;openModal(success)}
$('#payBtn').onclick=async()=>{const addr=$('#checkoutAddress').value.trim(),email=$('#checkoutEmail').value.trim();if(!addr||!email){alert('Please enter your service address and email to continue.');return}if(location.protocol==='file:'){alert('Start the app with “node server.js”, then open http://localhost:3000 in your browser. Do not open index.html directly.');return}const btn=$('#payBtn'), original=btn.innerHTML;btn.disabled=true;btn.textContent='Preparing secure checkout…';const details={plan:currentPlan.name,address:addr,email,paymentMethod:$('.method.active').textContent};try{const response=await fetch('/api/payment/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(details)});const order=await response.json();if(!response.ok)throw new Error(order.error || `Server returned ${response.status}`);if(order.provider==='demo'){const confirm=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...details,price:order.amount})});const result=await confirm.json();if(!confirm.ok)throw new Error(result.error);showActivation(result);return}if(!window.Razorpay)throw new Error('Razorpay Checkout could not load. Check your internet connection and try again.');const razorpay=new Razorpay({key:order.key,amount:order.amount,currency:order.currency,name:'NovaNet Fibre',description:`${details.plan} monthly subscription`,order_id:order.orderId,prefill:{email},theme:{color:'#5e4bd8'},handler:async payment=>{try{const verify=await fetch('/api/payment/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payment)});const result=await verify.json();if(!verify.ok)throw new Error(result.error);showActivation(result)}catch(error){alert(`Payment received, but verification needs attention: ${error.message}. Do not pay again; contact support with your payment ID.`)}}});razorpay.open()}catch(error){alert(`Checkout could not start: ${error.message}`)}finally{btn.disabled=false;btn.innerHTML=original}};
$('#speedBtn').onclick=()=>{const b=$('#speedBtn');b.innerHTML='<span>↻</span> Checking connection…';setTimeout(()=>b.innerHTML='<span>✓</span> 942 Mbps available',1100)};
$('#coverageBtn').onclick=()=>{const val=$('#addressInput').value.trim();$('#coverageResult').textContent=val?'✓ Great news — NovaNet fibre is available at this location.':'Enter your address to check availability.'};
const adminContent={
overview:`<div class="dash-stats"><div class="dash-card"><small>ACTIVE SUBSCRIBERS</small><b>12,483</b><em>↑ 8.4% this month</em></div><div class="dash-card"><small>MONTHLY REVENUE</small><b>₹84.2L</b><em>↑ 12.1% this month</em></div><div class="dash-card"><small>PAYMENTS TODAY</small><b>364</b><em>₹2.83L verified</em></div><div class="dash-card"><small>NETWORK UPTIME</small><b>99.99%</b><em>● All nodes healthy</em></div></div><div class="admin-grid"><div class="dash-box"><h3>Subscription growth</h3><div class="chart"><i data-day="MON" style="height:42%"></i><i data-day="TUE" style="height:58%"></i><i data-day="WED" style="height:49%"></i><i data-day="THU" style="height:72%"></i><i data-day="FRI" style="height:64%"></i><i data-day="SAT" style="height:83%"></i><i data-day="SUN" style="height:91%"></i></div></div><div class="dash-box"><h3>Automation status</h3><div class="notice"><b>✓ Recharge automation active</b>364 payments verified and plans activated today. Average completion: 4.2 seconds.</div><ul class="activity"><li><span>Payment verified: ₹799</span><span>2 min ago</span></li><li><span>Velocity plan activated</span><span>5 min ago</span></li><li><span>Invoice sent to customer</span><span>8 min ago</span></li></ul></div></div>`,
customers:`<div class="dash-box"><h3>Customer directory <span style="float:right;color:#777;font-weight:400">12,483 total customers</span></h3><table class="data-table"><thead><tr><th>CUSTOMER</th><th>PLAN</th><th>STATUS</th><th>RENEWAL</th></tr></thead><tbody><tr><td><b>Meera Sharma</b><br>meera@email.com</td><td>Momentum · 300 Mbps</td><td><span class="badge">Active</span></td><td>08 Aug 2026</td></tr><tr><td><b>Rohan Patel</b><br>rohan@email.com</td><td>Velocity · 1 Gbps</td><td><span class="badge">Active</span></td><td>24 Jul 2026</td></tr><tr><td><b>Anaya Singh</b><br>anaya@email.com</td><td>Essential · 100 Mbps</td><td><span class="badge">Active</span></td><td>01 Aug 2026</td></tr></tbody></table></div>`,
payments:`<div class="dash-box"><h3>Recent payments <span style="float:right;color:#548100">● All gateways online</span></h3><table class="data-table"><thead><tr><th>REFERENCE</th><th>CUSTOMER</th><th>METHOD</th><th>AMOUNT</th><th>STATE</th></tr></thead><tbody><tr><td>#NV-48291</td><td>Meera Sharma</td><td>UPI</td><td>₹799</td><td><span class="badge">Verified → Activated</span></td></tr><tr><td>#NV-48290</td><td>Rohan Patel</td><td>Card</td><td>₹1,299</td><td><span class="badge">Verified → Activated</span></td></tr><tr><td>#NV-48289</td><td>Anaya Singh</td><td>UPI</td><td>₹499</td><td><span class="badge">Verified → Activated</span></td></tr></tbody></table></div>`,
network:`<div class="dash-box"><h3>Network health <span style="float:right;color:#548100">● 14 / 14 nodes online</span></h3><div class="network-list"><div class="network-node"><div><b>Central Fibre Hub</b>Core infrastructure · 2,940 subscribers</div><span>99.99% uptime</span></div><div class="network-node"><div><b>North District Node</b>Distribution · 1,824 subscribers</div><span>99.98% uptime</span></div><div class="network-node"><div><b>Riverside Node</b>Distribution · 1,337 subscribers</div><span>99.99% uptime</span></div></div></div>`};
function showTab(tab){$('#adminContent').innerHTML=adminContent[tab];$$('.side-link').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab))}
$('#adminBtn').onclick=()=>{if(location.pathname.includes('portal.html')){$('#adminPanel').classList.add('open');showTab('overview')}else location.href='portal.html?view=admin'};$('#exitAdmin').onclick=()=>$('#adminPanel').classList.remove('open');$$('.side-link').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
