const q=s=>document.querySelector(s);const qa=s=>[...document.querySelectorAll(s)];
const api=async(path,options={})=>{const response=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=response.status===204?null:await response.json();if(!response.ok)throw new Error(data?.error||'Request failed.');return data};
const money=paise=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(paise/100);
const date=value=>value?new Date(value).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—';
let currentUser;
qa('[data-auth]').forEach(button=>button.onclick=()=>{qa('[data-auth]').forEach(x=>x.classList.toggle('selected',x===button));q('#loginForm').hidden=button.dataset.auth!=='login';q('#registerForm').hidden=button.dataset.auth!=='register';q('#authMessage').textContent=''});
async function submitForm(event,endpoint){event.preventDefault();const form=new FormData(event.currentTarget);const payload=Object.fromEntries(form.entries());try{const result=await api(endpoint,{method:'POST',body:JSON.stringify(payload)});currentUser=result.user;showPortal()}catch(error){q('#authMessage').textContent=error.message}}
q('#loginForm').onsubmit=e=>submitForm(e,'/api/auth/login');q('#registerForm').onsubmit=e=>submitForm(e,'/api/auth/register');
async function pay(plan){try{const order=await api('/api/payments/order',{method:'POST',body:JSON.stringify({plan})});if(!window.Razorpay)throw new Error('Razorpay Checkout could not load.');new Razorpay({key:order.key,amount:order.amount,currency:order.currency,name:'NovaNet Fibre',description:`${order.name} subscription`,order_id:order.orderId,prefill:{email:currentUser.email},theme:{color:'#5e4bd8'},handler:async payment=>{try{await api('/api/payments/verify',{method:'POST',body:JSON.stringify(payment)});await loadCustomer();alert('Payment verified. Your subscription is active.')}catch(error){alert(`Payment received, but verification needs support: ${error.message}`)}}}).open()}catch(error){alert(error.message)}}
async function loadCustomer(){const [dashboard,planData]=await Promise.all([api('/api/customer/dashboard'),api('/api/plans')]);const active=dashboard.subscriptions.find(x=>x.status==='active');q('#subscriptionContent').innerHTML=active?`<div class="plan-status"><div><h3>${active.name} <span>${active.speed_mbps} Mbps</span></h3><p>Active until ${date(active.ends_at)} · Provisioning: ${active.provision_status}</p></div><span class="status-chip">${active.status.toUpperCase()}</span></div>`:'<div class="notice">No active subscription yet. Choose a plan to get connected.</div>';q('#renewPlans').innerHTML=planData.plans.map(plan=>`<div class="renew-option"><div><strong>${plan.name} · ${plan.speed_mbps} Mbps</strong><small>${money(plan.price_paise)} / ${plan.duration_days} days</small></div><button data-plan="${plan.slug}">Choose</button></div>`).join('');qa('[data-plan]').forEach(button=>button.onclick=()=>pay(button.dataset.plan));q('#paymentsContent').innerHTML=dashboard.payments.length?dashboard.payments.map(payment=>`<div class="record"><div>${money(payment.amount_paise)}<small>${date(payment.created_at)} · ${payment.status}</small></div><b>${payment.provider_payment_id||'Pending'}</b></div>`).join(''):'<div class="record">No payments yet.</div>';q('#invoicesContent').innerHTML=dashboard.invoices.length?dashboard.invoices.map(invoice=>`<div class="record"><div>${invoice.invoice_number}<small>${date(invoice.created_at)}</small></div><a href="/api/invoices/${invoice.id}">Download PDF</a></div>`).join(''):'<div class="record">Invoices appear after payment verification.</div>'}
async function loadAdmin(){const data=await api('/api/admin/dashboard');q('#customerDashboard').hidden=true;q('#adminDashboard').hidden=false;q('#adminMetrics').innerHTML=`<div class="metric-card"><span class="eyebrow">CUSTOMERS</span><b>${data.metrics.customers}</b></div><div class="metric-card"><span class="eyebrow">MONTHLY REVENUE</span><b>${money(data.metrics.monthlyRevenuePaise)}</b></div><div class="metric-card"><span class="eyebrow">PAYMENTS</span><b>${data.payments.length}</b></div><div class="metric-card"><span class="eyebrow">SUBSCRIPTIONS</span><b>${data.subscriptions.length}</b></div>`;q('#adminPayments').innerHTML=`<table><thead><tr><th>CUSTOMER</th><th>PLAN</th><th>AMOUNT</th><th>STATE</th></tr></thead><tbody>${data.payments.map(p=>`<tr><td>${p.full_name}<br><small>${p.email}</small></td><td>${p.name}</td><td>${money(p.amount_paise)}</td><td>${p.status}</td></tr>`).join('')}</tbody></table>`;q('#adminSubscriptions').innerHTML=data.subscriptions.map(s=>`<div class="record"><div>${s.full_name}<small>${s.name} · until ${date(s.ends_at)}</small></div><b>${s.provision_status}</b></div>`).join('')||'<div class="record">No subscriptions yet.</div>'}
async function showPortal(){q('#authView').hidden=true;q('#portalView').hidden=false;q('#welcome').textContent=`Welcome back, ${currentUser.name || currentUser.email.split('@')[0]}.`;const admin=currentUser.role==='admin'||currentUser.role==='support';q('#adminViewBtn').hidden=!admin;if(new URLSearchParams(location.search).get('view')==='admin'&&admin) await loadAdmin();else await loadCustomer()}
q('#adminViewBtn').onclick=loadAdmin;q('#logoutBtn').onclick=async()=>{await api('/api/auth/logout',{method:'POST'});location.href='portal.html'};
(async()=>{try{const data=await api('/api/auth/me');currentUser=data.user;showPortal()}catch{}})();
