require('dotenv').config();
const express = require('express');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const cookieParser = require('cookie-parser');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const { Pool } = require('pg');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const nodemailer = require('nodemailer');

const ROOT = path.join(__dirname, '..');
const PORT = Number(process.env.PORT || 3000);
const isProduction = process.env.NODE_ENV === 'production';
for (const key of ['DATABASE_URL', 'JWT_SECRET', 'APP_BASE_URL', 'RAZORPAY_KEY_ID', 'RAZORPAY_KEY_SECRET', 'RAZORPAY_WEBHOOK_SECRET']) if (!process.env[key]) throw new Error(`${key} must be configured before starting the production server.`);
if (process.env.JWT_SECRET.length < 48) throw new Error('JWT_SECRET must be at least 48 characters.');
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: isProduction ? { rejectUnauthorized: false } : false, max: 12 });
const app = express();
app.set('trust proxy', 1);
app.use(helmet({ contentSecurityPolicy: { directives: { defaultSrc:["'self'"], scriptSrc:["'self'",'https://checkout.razorpay.com'], styleSrc:["'self'",'https://fonts.googleapis.com',"'unsafe-inline'"], fontSrc:["'self'",'https://fonts.gstatic.com'], connectSrc:["'self'"], imgSrc:["'self'",'data:'] } } }));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 300, standardHeaders: 'draft-8', legacyHeaders: false }));
app.use(cookieParser());
app.use((req, res, next) => { if (['POST','PUT','PATCH','DELETE'].includes(req.method) && req.path !== '/api/webhooks/razorpay') { const origin = req.get('origin'); if (origin && origin !== process.env.APP_BASE_URL) return res.status(403).json({ error: 'Invalid request origin.' }); } next(); });

const authLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 10, standardHeaders: 'draft-8', legacyHeaders: false });
function error(res, status, message) { return res.status(status).json({ error: message }); }
function sign(user) { return jwt.sign({ sub:user.id, role:user.role, email:user.email }, process.env.JWT_SECRET, { expiresIn:'8h', issuer:'novanet', audience:'novanet-portal' }); }
function setSession(res, user) { res.cookie('novanet_session', sign(user), { httpOnly:true, secure:isProduction, sameSite:'lax', maxAge:8 * 60 * 60 * 1000, path:'/' }); }
function requireAuth(req, res, next) { try { const token=req.cookies.novanet_session; if (!token) return error(res,401,'Please sign in.'); req.user=jwt.verify(token,process.env.JWT_SECRET,{issuer:'novanet',audience:'novanet-portal'}); next(); } catch { return error(res,401,'Your session has expired. Please sign in again.'); } }
function requireRole(...roles) { return (req,res,next) => roles.includes(req.user.role) ? next() : error(res,403,'You do not have permission for this action.'); }
function money(paise) { return `₹${(paise / 100).toFixed(2)}`; }
function hmacValid(message, signature, secret) { const expected=crypto.createHmac('sha256',secret).update(message).digest('hex'); return signature && signature.length === expected.length && crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected)); }
async function razorpay(endpoint, payload) { const response=await fetch(`https://api.razorpay.com${endpoint}`,{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${process.env.RAZORPAY_KEY_ID}:${process.env.RAZORPAY_KEY_SECRET}`).toString('base64')}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}); const data=await response.json(); if(!response.ok) throw new Error(data.error?.description || 'Razorpay request failed.'); return data; }
function invoicePath(id) { const directory=path.join(ROOT,'storage','invoices'); fs.mkdirSync(directory,{recursive:true}); return path.join(directory,`${id}.pdf`); }
function createInvoiceFile(invoice, customer, plan, payment) { return new Promise((resolve,reject)=>{ const output=invoicePath(invoice.id); const doc=new PDFDocument({margin:50}); const stream=fs.createWriteStream(output); doc.pipe(stream); doc.fontSize(24).fillColor('#5e4bd8').text('Sai Shradha Fibre',50,50); doc.fillColor('#101027').fontSize(18).text('Tax Invoice',50,92); doc.fontSize(10).fillColor('#555').text(`Invoice: ${invoice.invoice_number}`,50,125).text(`Date: ${new Date().toLocaleDateString('en-IN')}`,50,141).text(`Customer: ${customer.full_name}`,50,175).text(customer.email,50,191).text(customer.service_address,50,207); doc.moveTo(50,245).lineTo(545,245).stroke('#ddd'); doc.fillColor('#101027').fontSize(12).text(`${plan.name} fibre subscription`,50,265).text(`${plan.speed_mbps} Mbps · ${plan.duration_days} days`,50,283); doc.fontSize(16).text(money(payment.amount_paise),450,265,{width:95,align:'right'}); doc.moveTo(50,320).lineTo(545,320).stroke('#ddd'); doc.fontSize(10).fillColor('#555').text(`Payment reference: ${payment.provider_payment_id}`,50,340).text('Shree Sai Shradha Infra Private Limited',50,385).text('Jijamata Complex, Bajarpeth Rd, Otur, Maharashtra 412409',50,401); doc.end(); stream.on('finish',()=>resolve(output)); stream.on('error',reject); }); }
async function sendNotifications(customer, plan, invoiceFile) { const tasks=[]; if(process.env.SMTP_HOST && process.env.MAIL_FROM) { const mailer=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT || 587),secure:false,auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}:undefined}); tasks.push(mailer.sendMail({from:process.env.MAIL_FROM,to:customer.email,subject:'Sai Shradha Fibre plan activated',text:`Your ${plan.name} plan is active. Support: 9960007310.`,attachments:invoiceFile?[{filename:'sai-shradha-invoice.pdf',path:invoiceFile}]:[]})); } if(process.env.WHATSAPP_PHONE_NUMBER_ID && process.env.WHATSAPP_ACCESS_TOKEN && customer.mobile) tasks.push(fetch(`https://graph.facebook.com/v22.0/${process.env.WHATSAPP_PHONE_NUMBER_ID}/messages`,{method:'POST',headers:{Authorization:`Bearer ${process.env.WHATSAPP_ACCESS_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:customer.mobile.replace(/\D/g,''),type:'text',text:{body:`Sai Shradha Fibre: your ${plan.name} plan is active. Support: 9960007310.`}})})); await Promise.allSettled(tasks); }
async function provisionRouter(customer, enabled) { if(process.env.MIKROTIK_ENABLED !== 'true') return { status:'not_configured' }; if(!customer.router_secret_id) return { status:'awaiting_router_mapping' }; const response=await fetch(`${process.env.MIKROTIK_BASE_URL}/ppp/secret/${encodeURIComponent(customer.router_secret_id)}`,{method:'PATCH',headers:{Authorization:`Basic ${Buffer.from(`${process.env.MIKROTIK_USERNAME}:${process.env.MIKROTIK_PASSWORD}`).toString('base64')}`,'Content-Type':'application/json'},body:JSON.stringify({disabled:enabled?'false':'true'})}); if(!response.ok) throw new Error('Router provisioning failed.'); return { status:enabled?'enabled':'suspended' }; }
async function fulfilPayment(payment, paymentId) { const client=await pool.connect(); try { await client.query('BEGIN'); const current=(await client.query('SELECT p.*, pl.name AS plan_name, pl.speed_mbps, pl.duration_days, u.full_name, u.email, cp.mobile, cp.service_address, cp.router_secret_id FROM payments p JOIN plans pl ON pl.id=p.plan_id JOIN users u ON u.id=p.user_id JOIN customer_profiles cp ON cp.user_id=u.id WHERE p.id=$1 FOR UPDATE',[payment.id])).rows[0]; if(!current) throw new Error('Payment not found.'); if(current.status === 'verified') { await client.query('COMMIT'); return current; } await client.query('UPDATE payments SET status=$1, provider_payment_id=$2, verified_at=now() WHERE id=$3',['verified',paymentId,current.id]); const latest=(await client.query("SELECT ends_at FROM subscriptions WHERE user_id=$1 AND status='active' ORDER BY ends_at DESC LIMIT 1",[current.user_id])).rows[0]; const base=latest?.ends_at && new Date(latest.ends_at) > new Date() ? new Date(latest.ends_at) : new Date(); const endsAt=new Date(base.getTime() + current.duration_days * 86400000); const subscription=(await client.query("INSERT INTO subscriptions (user_id,plan_id,payment_id,status,starts_at,ends_at,provision_status) VALUES ($1,$2,$3,'active',now(),$4,'pending') RETURNING *",[current.user_id,current.plan_id,current.id,endsAt])).rows[0]; const invoice=(await client.query('INSERT INTO invoices (invoice_number,user_id,payment_id) VALUES ($1,$2,$3) RETURNING *',[`NV-${new Date().getFullYear()}-${crypto.randomInt(100000,999999)}`,current.user_id,current.id])).rows[0]; await client.query('COMMIT'); try { const result=await provisionRouter(current,true); await pool.query('UPDATE subscriptions SET provision_status=$1, provisioned_at=CASE WHEN $1=$2 THEN now() ELSE NULL END WHERE id=$3',[result.status,'enabled',subscription.id]); const file=await createInvoiceFile(invoice,current,{name:current.plan_name,speed_mbps:current.speed_mbps,duration_days:current.duration_days},current); await pool.query('UPDATE invoices SET file_path=$1 WHERE id=$2',[file,invoice.id]); await sendNotifications(current,{name:current.plan_name},file); } catch (provisionError) { await pool.query('UPDATE subscriptions SET provision_status=$1 WHERE id=$2',[`action_required: ${provisionError.message}`,subscription.id]); } return {...current, ends_at:endsAt}; } catch(err) { await client.query('ROLLBACK'); throw err; } finally { client.release(); } }

app.post('/api/webhooks/razorpay', express.raw({type:'application/json',limit:'1mb'}), async (req,res) => { const signature=req.get('x-razorpay-signature'); const eventId=req.get('x-razorpay-event-id'); const raw=req.body.toString('utf8'); if(!hmacValid(raw,signature,process.env.RAZORPAY_WEBHOOK_SECRET)) return error(res,400,'Invalid webhook signature.'); if(!eventId) return error(res,400,'Webhook event ID missing.'); try { const seen=await pool.query('SELECT 1 FROM webhook_events WHERE provider=$1 AND event_id=$2',['razorpay',eventId]); if(seen.rowCount) return res.status(200).json({received:true,duplicate:true}); const event=JSON.parse(raw); if(['payment.captured','order.paid'].includes(event.event)) { const entity=event.payload.payment?.entity; if(entity?.order_id && entity?.id) { const payment=(await pool.query('SELECT * FROM payments WHERE provider_order_id=$1',[entity.order_id])).rows[0]; if(payment) await fulfilPayment(payment,entity.id); } } await pool.query('INSERT INTO webhook_events (provider,event_id) VALUES ($1,$2) ON CONFLICT DO NOTHING',['razorpay',eventId]); return res.status(200).json({received:true}); } catch(err) { console.error('Webhook error',err.message); return error(res,500,'Webhook processing failed.'); } });
app.use(express.json({limit:'100kb'}));

app.post('/api/auth/register',authLimiter,async(req,res)=>{ const {fullName,email,password,mobile,address}=req.body || {}; if(!fullName || !/^\S+@\S+\.\S+$/.test(email || '') || typeof password !== 'string' || password.length < 12 || !mobile || !address) return error(res,400,'Enter a name, valid email, mobile number, address, and password of at least 12 characters.'); const client=await pool.connect(); try { const hash=await bcrypt.hash(password,12); await client.query('BEGIN'); const user=(await client.query('INSERT INTO users (full_name,email,password_hash) VALUES ($1,$2,$3) RETURNING id,full_name,email,role',[fullName.trim(),email.trim().toLowerCase(),hash])).rows[0]; await client.query('INSERT INTO customer_profiles (user_id,mobile,service_address) VALUES ($1,$2,$3)',[user.id,mobile.trim(),address.trim()]); await client.query('COMMIT'); setSession(res,user); res.status(201).json({user:{name:user.full_name,email:user.email,role:user.role}}); } catch(err) { await client.query('ROLLBACK'); return error(res,err.code==='23505'?409:500,err.code==='23505'?'An account already exists for this email.':'Could not create account.'); } finally { client.release(); } });
app.post('/api/auth/login',authLimiter,async(req,res)=>{ const {email,password}=req.body || {}; const user=(await pool.query('SELECT id,full_name,email,password_hash,role FROM users WHERE email=$1',[String(email || '').trim().toLowerCase()])).rows[0]; if(!user || !(await bcrypt.compare(String(password || ''),user.password_hash))) return error(res,401,'Incorrect email or password.'); setSession(res,user); res.json({user:{name:user.full_name,email:user.email,role:user.role}}); });
app.post('/api/auth/logout',(req,res)=>{res.clearCookie('novanet_session',{path:'/'});res.status(204).end();});
app.get('/api/auth/me',requireAuth,(req,res)=>res.json({user:req.user}));
app.get('/api/plans',async(req,res)=>res.json({plans:(await pool.query('SELECT slug,name,speed_mbps,price_paise,duration_days FROM plans WHERE active=true ORDER BY price_paise')).rows}));
app.post('/api/payments/order',requireAuth,async(req,res)=>{ try { const plan=(await pool.query('SELECT * FROM plans WHERE slug=$1 AND active=true',[req.body?.plan])).rows[0]; if(!plan) return error(res,400,'Selected plan is unavailable.'); const payment=(await pool.query('INSERT INTO payments (user_id,plan_id,amount_paise) VALUES ($1,$2,$3) RETURNING id',[req.user.sub,plan.id,plan.price_paise])).rows[0]; const order=await razorpay('/v1/orders',{amount:plan.price_paise,currency:'INR',receipt:`nv_${payment.id.replace(/-/g,'').slice(0,24)}`,notes:{payment_id:payment.id,user_id:req.user.sub,plan:plan.slug}}); await pool.query('UPDATE payments SET provider_order_id=$1 WHERE id=$2',[order.id,payment.id]); res.status(201).json({key:process.env.RAZORPAY_KEY_ID,orderId:order.id,amount:order.amount,currency:order.currency,name:plan.name}); } catch(err) { console.error('Order error',err.message); return error(res,502,'Could not create secure payment order.'); } });
app.post('/api/payments/verify',requireAuth,async(req,res)=>{ const {razorpay_order_id:orderId,razorpay_payment_id:paymentId,razorpay_signature:signature}=req.body || {}; const payment=(await pool.query('SELECT * FROM payments WHERE provider_order_id=$1 AND user_id=$2',[orderId,req.user.sub])).rows[0]; if(!payment || !hmacValid(`${orderId}|${paymentId}`,signature,process.env.RAZORPAY_KEY_SECRET)) return error(res,400,'Payment signature is invalid.'); try { const active=await fulfilPayment(payment,paymentId); res.json({status:'activated',endsAt:active.ends_at}); } catch { return error(res,500,'Payment verified, but activation needs attention. Please contact support.'); } });
app.get('/api/customer/dashboard',requireAuth,async(req,res)=>{ const [profile,subscriptions,payments,invoices]=await Promise.all([pool.query('SELECT full_name,email,mobile,service_address,router_username FROM users JOIN customer_profiles ON customer_profiles.user_id=users.id WHERE users.id=$1',[req.user.sub]),pool.query('SELECT s.status,s.starts_at,s.ends_at,s.provision_status,p.name,p.speed_mbps FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.user_id=$1 ORDER BY s.created_at DESC',[req.user.sub]),pool.query('SELECT amount_paise,status,provider_payment_id,verified_at,created_at FROM payments WHERE user_id=$1 ORDER BY created_at DESC',[req.user.sub]),pool.query('SELECT id,invoice_number,created_at FROM invoices WHERE user_id=$1 ORDER BY created_at DESC',[req.user.sub])]); res.json({profile:profile.rows[0],subscriptions:subscriptions.rows,payments:payments.rows,invoices:invoices.rows}); });
app.get('/api/admin/dashboard',requireAuth,requireRole('admin','support'),async(req,res)=>{ const [customers,revenue,payments,subscriptions]=await Promise.all([pool.query('SELECT count(*)::int AS total FROM users WHERE role=$1',['customer']),pool.query("SELECT COALESCE(sum(amount_paise),0)::int AS paise FROM payments WHERE status='verified' AND verified_at >= date_trunc('month',now())"),pool.query("SELECT p.provider_payment_id,u.full_name,u.email,pl.name,p.amount_paise,p.status,p.verified_at FROM payments p JOIN users u ON u.id=p.user_id JOIN plans pl ON pl.id=p.plan_id ORDER BY p.created_at DESC LIMIT 20"),pool.query("SELECT s.status,s.provision_status,s.ends_at,u.full_name,u.email,pl.name FROM subscriptions s JOIN users u ON u.id=s.user_id JOIN plans pl ON pl.id=s.plan_id ORDER BY s.created_at DESC LIMIT 20")]); res.json({metrics:{customers:customers.rows[0].total,monthlyRevenuePaise:revenue.rows[0].paise},payments:payments.rows,subscriptions:subscriptions.rows}); });
app.get('/api/invoices/:id',requireAuth,async(req,res)=>{ const invoice=(await pool.query('SELECT i.file_path FROM invoices i WHERE i.id=$1 AND i.user_id=$2',[req.params.id,req.user.sub])).rows[0]; if(!invoice?.file_path || !fs.existsSync(invoice.file_path)) return error(res,404,'Invoice not available.'); res.download(invoice.file_path); });

app.get('/',(req,res)=>res.sendFile(path.join(ROOT,'index.html'))); app.get('/index.html',(req,res)=>res.sendFile(path.join(ROOT,'index.html'))); app.get('/portal.html',(req,res)=>res.sendFile(path.join(ROOT,'portal.html'))); app.get('/styles.css',(req,res)=>res.sendFile(path.join(ROOT,'styles.css'))); app.get('/portal.css',(req,res)=>res.sendFile(path.join(ROOT,'portal.css'))); app.get('/app.js',(req,res)=>res.sendFile(path.join(ROOT,'app.js'))); app.get('/portal.js',(req,res)=>res.sendFile(path.join(ROOT,'portal.js')));
app.use((req,res)=>error(res,404,'Not found.'));
app.listen(PORT,()=>console.log(`Sai Shradha Fibre production server listening on ${PORT}`));
